### ISSUE TITLE
Client randomly disconnects on large test suites

### ISSUE THREAD

**Issue by cgewecke** [ConsenSys-archive/ganache-cli-archive#503] opened 2018-04-07 16:49 UTC
Hi @benjamincburns  :) This is a companion issue to [truffle 729](https://github.com/trufflesuite/truffle/issues/729) and possibly a duplicate of #417 / #453 here. @barakman has recently [posted a script](https://github.com/trufflesuite/truffle/issues/729#issuecomment-379433643) in 729 that consistently reproduces the disconnect for them. 

Example of the error:

```shell
2) Contract: ... "after each" hook: after test for "...":
     Error: Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)

      at ProviderError.ExtendableError (C:\Users\...\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-error\index.js:10:1)
      at new ProviderError (C:\Users\...\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-provider\error.js:17:1)
      at C:\Users\...\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-provider\wrapper.js:71:1
      at C:\Users\...\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-provider\wrapper.js:129:1
      at XMLHttpRequest.request.onreadystatechange (C:\Users\...\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\...\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (C:\Users\...\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
      at XMLHttpRequest._onHttpRequestError (C:\Users\...\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:544:1)
      at ClientRequest.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:414:1)
      at Socket.socketErrorListener (_http_client.js:387:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by barakman** [comment] 2018-05-08 18:43
Added more information at [truffle 729](https://github.com/trufflesuite/truffle/issues/729).

**Comment by benjamincburns** [comment] 2018-08-13 22:15
From the sister thread it sounds like this is a resource limitation issue caused by the client side not closing connections. As a result, I'm closing this. If it turns out that it's ganache that's improperly hogging file handles/connections, please let me know.

However please also be aware of TCP `FIN_WAIT` states when handling lots of rapid connections. There's no good way for any application to get around this (this is a system-level issue).

**Closed as completed by benjamincburns** 2018-08-13 22:15 UTC

**Comment by barakman** [comment] 2018-08-15 05:59
@benjamincburns:
Thanks.
Client side, to my understanding, is Truffle in this case (while server side is Ganache).
So in my opinion this issue shouldn't be closed based on your argument, because the problem is in Truffle.
Second, as I have explained on [truffle 729](https://github.com/trufflesuite/truffle/issues/729), the problem can be solved by applying a fix in Truffle source code.

**Comment by benjamincburns** [comment] 2018-08-15 19:52
@barakman we use github issues to track upcoming/outstanding work on the project. If the problem is in truffle as you say and there's no work to be done in ganache, it's appropriate to close this issue, especially since trufflesuite/truffle#729 more appropriately tracks the work necessary to fix this issue.

**Comment by barakman** [comment] 2018-08-15 20:33
@benjamincburns:
Arrrgh, didn't notice this was a Ganache thread up until now.
My apologies.
