### ISSUE TITLE
`delegatecall` incorrectly handling exceptions

### ISSUE THREAD

**Issue by abandeali1** [ConsenSys-archive/ganache-cli-archive#355] opened 2017-07-23 20:28 UTC
## Expected Behavior
`delegatecall` is expected to return `true` (if the sub-call was successful) or `false` (if the sub-call threw an exception)

## Current Behavior
Instead of returning `false` when unsuccessful, `delegatecall` throws an exception, causing the entire transaction to fail.

## Steps to Reproduce
```
pragma solidity ^0.4.11;

import "truffle/Assert.sol";

contract DelegatecallThrow {
    function doDelegatecallThrow()  returns (bool) {
        return address(this).delegatecall(bytes4(keccak256("doThrow()")));
    }
    function doThrow() {
        throw;
    }
}

contract TestDelegatecallThrow {
    function testDelegatecallThrow() {
        DelegatecallThrow delegatecallThrow = new DelegatecallThrow();
        bool returnedFalse = !delegatecallThrow.doDelegatecallThrow();
        Assert.isTrue(returnedFalse, "it should have returned false");
    }
}
```

When I run `truffle test` with testrpc, the test fails with `Error: VM Exception while processing transaction: invalid opcode`. The test passes when using geth.

## Context
I am trying to create a version of a function that always fails silently.

## Your Environment
* Version used: Tested with both 4.0.1 and 3.0.3

**Comment by cdetrio** [comment] 2017-07-25 11:28
this should be fixed by upgrading the ethereumjs-vm version to 2.1.0 (testrpc is currently using ethereumjs-vm 2.0.1 in the yarn.lock file).

**Comment by abandeali1** [comment] 2017-07-26 23:05
Upgrading to 2.1.0 did not fix this, as far as I can tell.

**Comment by lastperson** [comment] 2017-10-20 23:55
Issue is still not resolved as of 4.1.3. I face it while using assembly `delegatecall`, it is always return 0, even if the call was successful.

**Comment by lastperson** [comment] 2017-10-30 08:09
Can't reproduce in Remix. Though it is constantly reproducible in testrpc, up to 5.0.1 beta.
Actual:
Failed `assembly delegatecall` -> exception.
Successful `assembly delegatecall` -> 0.

Expected:
Failed `assembly delegatecall` -> 0.
Successful `assembly delegatecall` -> 1.

**Comment by axic** [comment] 2017-10-30 14:31
I think the above is due to `revert` not being implemented in the old VM used by testrpc, while Remix already uses the Byzantium compatible VM. In the above Solidity code `throw` emits `revert`.

**Comment by benjamincburns** [comment] 2017-11-04 04:33
As of TestRPC v6.0.1, `REVERT` is properly handled. That said, if it's reproducible in 5.0.1 beta, it's likely also reproducible in 6.0.1.

I'm not sure if this is our issue, or an issue in ethereumjs-vm. I'll do my best to dig into it shortly, but if anyone else feels motivated to help out, I'd be much obliged for a PR.

cc @jwasinger

**Comment by lastperson** [comment] 2017-11-16 09:24
Doesn't reproduce on 6.0.3, works as expected. Probably can be closed.

**Comment by benjamincburns** [comment] 2017-11-23 03:53
Thanks, @lastperson!

**Closed as completed by benjamincburns** 2017-11-23 03:53 UTC
Labels: help wanted
