### ISSUE TITLE
eth_estimateGas returns wrong estimation

### ISSUE THREAD

**Issue by lastperson** [ConsenSys-archive/ganache-cli-archive#58] opened 2016-04-05 10:08 UTC
Hi, I'm currently playing around with browser-solidity connected to the testrpc, they have a logic there, that before each transaction to the real node (and they assume testrpc to be real node of course) they call `estimateGas`, then adjust gas for transaction to what was returned by estimation, then send transaction. The problem is, that for a transaction that will actually eat `225444` gas, it estimates only `75444`. There is also situations when the estimate is bigger than actual use.

**Comment by tcoulter** [comment] 2016-04-05 14:22
Hi there. Note that the TestRPC has a gas price of 1 Wei. Also, please
submit code that we can use to reproduce the issue.

**Comment by lastperson** [comment] 2016-04-06 06:09
Deploy: estimate 537426, usage 552426, diff 15000
Add: estimate 61476, usage 151476, diff 90000
Transfer: estimate 47091, usage 77091, diff 30000

```
contract EstimateGas {
    event Add(bytes32 name, bytes32 description, uint value, address owner);

    struct Test {
        bytes32 name;
        bytes32 description;
        uint[] balances;
        mapping(address => uint) owners;
    }

    mapping(bytes32 => uint) index;
    Test[] tests;

    function EstimateGas() {
        tests.length++;
    }

    function add(bytes32 _name, bytes32 _description, uint _value) returns(bool) {
        if (index[_name] != 0) {
            return false;
        }
        uint pos = tests.length++;
        tests[pos].name = _name;
        tests[pos].description = _description;
        tests[pos].balances.length = 2;
        tests[pos].balances[1] = _value;
        tests[pos].owners[msg.sender] = 1;
        index[_name] = pos;
        Add(_name, _description, _value, msg.sender);
        return true;
    }

    function transfer(address _to, uint _value, bytes32 _name) returns(bool) {
        uint pos = index[_name];
        if (pos == 0) {
            return false;
        }

        uint posFrom = tests[pos].owners[msg.sender];
        if (posFrom == 0) {
            return false;
        }

        if (tests[pos].balances[posFrom] < _value) {
            return false;
        }

        uint posTo = tests[pos].owners[_to];
        if (posTo == 0) {
            uint posBal = tests[pos].balances.length++;
            tests[pos].owners[_to] = posBal;
            posTo = posBal;
        }

        if (tests[pos].balances[posTo] + _value < tests[pos].balances[posTo]) {
            return false;
        }
        tests[pos].balances[posFrom] -= _value;
        tests[pos].balances[posTo] += _value;

        return true;
    }
}
```

**Comment by tcoulter** [comment] 2016-04-06 18:19
You're comparing to geth right? The gas usages will be different depending on gas price. Set geth's gas price to 1 wei (if that's even possible) before making the comparison. Otherwise you're comparing apples and oranges.

**Comment by axic** [comment] 2016-04-06 18:23
@tcoulter `estimateGas` returns the gas value, the same what you would pass as `gasLimit`.

This is then multiplied by `gasPrice` to get a cost in Ethers and that is how much will be deducted after a transaction.

**Comment by tcoulter** [comment] 2016-04-06 18:30
@axic Ah, looks like I misunderstood what @lastperson was saying. So: usage != estimate on the TestRPC -- geth or browsersolidity doesn't matter here. Is that correct? @lastperson can you confirm?

**Comment by lastperson** [comment] 2016-04-07 00:59
@tcoulter, yes, the problem is exactly that TestRPC usage is not consistent with TestRPC estimation.

**Comment by kumavis** [comment] 2016-08-22 22:43
issue is prolly in provider-engine https://github.com/MetaMask/provider-engine/issues/80

**Comment by tcoulter** [comment] 2016-08-24 19:11
I'm having trouble reproducing this with the same results as you. However, I did notice some issues in the most recent TestRPC where, when asking for a transaction's receipt, `gasUsed` -- the gas used for that transaction -- was 0, and `cumulativeGasUsed` -- the gas used for the whole block -- was the total gas of the transaction.

I've committed this fix to master. As well, I wrote a couple tests that use the exact code you specified above to compare gas estimation with actual usage. For me the tests pass and estimation matches usage. You can find those tests here: https://github.com/ethereumjs/testrpc/blob/master/test/gas.js

@area @lastperson can one of you review these fixes and let me know if they work for you? To do so, do the following:

```
$ git clone https://github.com/ethereumjs/testrpc.git
$ cd testrpc
$ npm install
$ ./bin/testrpc
```

I would be very happy to know if this was the correct fix. If so, I can push out a new version asap.

**Comment by benjamincburns** [comment] 2017-10-18 17:15
@area @lastperson @tcoulter - closing this issue as tests are passing and there has been no response in over a year.

I'm not at all averse to reopening if it turns out there are still issues in this area.

**Closed as completed by benjamincburns** 2017-10-18 17:15 UTC
Labels: bug

**Comment by benjamincburns** [comment] 2017-10-18 17:17
@axic - I think maybe Tim meant to notify you before instead of @area? If so, sorry for the noise, @area...
