### ISSUE TITLE
Calling getBalance on contract results in 3 * sent amount

### ISSUE THREAD

**Issue by illuzen** [ConsenSys-archive/ganache-cli-archive#348] opened 2017-07-17 00:21 UTC
I send x wei to a contract address with 

`web3.eth.sendTransaction({from: accounts[0], to: contract.address, value: x})`

then I check the balance

`web3.eth.getBalance(contract.address)`

It returns 3 * x...

This is consistent if I change x. It also deducts accounts[0] balance by 3 * x. Regardless of what my contract does, this should not be happening. Oddly enough, the token distribution amounts are changed by the correct amounts, without the 3x factor.

Truffle v3.4.4
OSX 10.12.4
TestRPC v4.0.1

**Comment by illuzen** [comment] 2017-07-17 01:35
More data:
```
      // this results in multiplication of msg.value by 2 unless I comment out the rest of the function...
      uint256 createdTokens = tokensPerEther * msg.value;
      // this actually multiplies msg.value by 3 even tho tokensPerEther != 3
      // using SafeMathLib for uint here
      uint256 createdTokens = tokensPerEther.times(msg.value);
```

Also, confirmed this doesn't happen on mainnet...

**Comment by ccowell** [comment] 2018-10-11 18:38
Thank for reporting this, @illuzen! We're going to go ahead and close this issue as we've been unable to reproduce the issue using the latest version of ganache-cli. If you are still experiencing this issue please open a new issue with steps on how to reproduce and we'll look into it again.

**Closed as completed by ccowell** 2018-10-11 18:38 UTC
Labels: needs validation, priority-high
