### ISSUE TITLE
docker container mentioned in the docs is not available

### ISSUE THREAD

**Issue by kvbik** [ConsenSys-archive/ganache-cli-archive#331] opened 2017-06-23 17:22 UTC
In the `README.md` there is a `Docker` section. It seems the container is not available on the Docker HUB anymore.

https://github.com/ethereumjs/testrpc#docker

```
Jakubs-MacBook:wt-env kvbik$ docker run -d -p 8545:8545 ethereumjs/testrpc:latest
Pulling repository docker.io/ethereumjs/testrpc
docker: Error: image ethereumjs/testrpc:latest not found.
```

**Comment by MHPppflueger** [comment] 2017-07-05 12:58
To build the Docker container from source:

```
git clone https://github.com/ethereumjs/testrpc.git && cd testrpc
docker build -t ethereumjs/testrpc .
```

after that you can use your docker run ... command

**Comment by ezynda3** [comment] 2017-07-05 22:47
`Error: Cannot find module '/src/bin/testrpc'` after building the container from source like the README suggests.

**Comment by MHPppflueger** [comment] 2017-07-06 07:06
Something seems broken then.
I would suggest using a Image directly from Dockerhub. I tested https://hub.docker.com/r/harshjv/testrpc/ and it works.

**Comment by kvbik** [comment] 2017-07-06 08:48
Don't get me wrong @MHPppflueger I am happy this project provides `Dockerfile` for building a container for it. But the point of this issue is, that the official documentation is mentioning an already provided docker container available on Docker HUB. Which, if I am not mistaken (could be an output of this issue too) is not available any more (or never was, i don't know).

**Comment by kvbik** [comment] 2017-07-06 08:49
I am using testrpc docker images provided by other people.

**Comment by MHPppflueger** [comment] 2017-07-07 14:24
I got your point. This should be fixed ofc ;)
I just wanted to provide you a workaround to save you some time waiting for a fix.

**Comment by ezynda3** [comment] 2017-07-07 14:26
I created a PR for this. Not sure why the tests are failing though. Seems unrelated to the fix. https://github.com/ethereumjs/testrpc/pull/343

**Comment by mikeshultz** [comment] 2017-07-17 19:30
Duplicate of #228

**Comment by a-stankevich** [comment] 2017-07-18 19:28
@mikeshultz how is this a duplicate of #228?

**Comment by mikeshultz** [comment] 2017-07-18 20:06
@a-stankevich Looks like I fat-fingered it.  Duplicate of #288

**Comment by phra** [comment] 2017-10-04 20:26
really? at least remove the mention from the README!

**Comment by benjamincburns** [comment] 2017-11-21 06:18
https://hub.docker.com/r/trufflesuite/ganache-cli

Docker container mentioned in docs is now available. ;-)

**Closed as completed by benjamincburns** 2017-11-21 06:18 UTC

**Comment by kvbik** [comment] 2017-11-22 13:30
i don't see the `hub.docker` link in the docs btw..
