### ISSUE TITLE
TypeError: Cannot read property 'pop' of undefined when restarting from existing `--db`

### ISSUE THREAD

**Issue by tsuberim** [ConsenSys-archive/ganache-cli-archive#600] opened 2018-11-26 16:25 UTC
## Expected Behavior

Ganache should behave exactly the same after restarting from an existing `db` as if it were not restarted at all.

## Current Behavior

`ganache-cli` does not behave the same when starting from an existing `db` directory. It wrongly rejects a transaction with correct `nonce` and crashes when given the `nonce` it (wrongly) expects.

## Steps to Reproduce (for bugs)

1. `git clone https://github.com/tsuberim/ganache-bug.git`
2. `npm install`
3. `npm run ganache` - start ganache command in one terminal tab for the first time (creating db directory `./asdf`)
4. `node crash.js` - run a simple script in another tab sending 1 ether to an account.
5. Stop ganache.
6. `npm run ganache` - start ganache again (now using existing db).
7. `node crash.js` - run simple script again.
8. The script fails with:
   ```
   Error: Returned error: the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: 1
   at Object.ErrorResponse (/home/tsuberim/projects/ganache-test/node_modules/web3-core-helpers/src/errors.js:29:16)
   at /home/tsuberim/projects/ganache-test/node_modules/web3-core-requestmanager/src/index.js:140:36
   at XMLHttpRequest.request.onreadystatechange (/home/tsuberim/projects/ganache-test/node_modules/web3-providers-http/src/index.js:91:13)
   at XMLHttpRequestEventTarget.dispatchEvent (/home/tsuberim/projects/ganache-test/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
   at XMLHttpRequest._setReadyState (/home/tsuberim/projects/ganache-test/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
   at XMLHttpRequest._onHttpResponseEnd (/home/tsuberim/projects/ganache-test/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
   at IncomingMessage.<anonymous> (/home/tsuberim/projects/ganache-test/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
   at IncomingMessage.emit (events.js:187:15)
   at endReadableNT (_stream_readable.js:1094:12)
   at process._tickCallback (internal/process/next_tick.js:63:19)
   ```
9. If using `nonce: 0`, ganache fails with:
   ```
   TypeError: Cannot read property 'pop' of undefined
   at CheckpointTrie.Trie._updateNode (/home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:360:24)
   at /home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:107:16
   at /home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:461:14
   at processNode (/home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:471:23)
   at /home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:457:5
   at /home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:180:7
   at /home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:75:7
   at /home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
   at /home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:269:32
   at /home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
   at /home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:71:7
   at /home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:157:9
   at /home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/lib/database/levelupobjectadapter.js:41:16
   at /home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/level-sublevel/shell.js:101:15
   at /home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/level-sublevel/nut.js:121:19
   at /home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/encoding-down/index.js:51:21
   at /home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/node_modules/cachedown/index.js:58:21
   at ReadFileContext.callback (/home/tsuberim/projects/ganache-test/node_modules/ganache-cli/node_modules/ganache-core/lib/database/filedown.js:26:14)
   at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)
   ```

**Note: The script succeeds when not restarting ganache midway.**

## Your Environment
* Version used: `Ganache CLI v6.2.3 (ganache-core: 2.3.1)`
* Version of Truffle/Remix/Other tools used: `web3@1.0.0-beta.36`
* NodeJS Version: `v10.13.0`
* Operating System and version (include distro if Linux): 
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```
* Link to your project or repro gist: https://github.com/tsuberim/ganache-bug
* Commit hash to use with above link for reproduction: `606cccd494479e88f25cfbb22cd683d842e61b27`
* I intend to submit a pull request to fix this issue: [ ]

**Comment by koirikivi** [comment] 2018-11-27 14:01
I think I encountered the same problem when using `--blockTime`. 

```
$ mkdir ganache-db
$ ganache-cli --db ganache-db --blockTime 1
# Quit the process CTRL-C
$ ganache-cli --db ganache-db --blockTime 1
```

The first launch works correctly, but when launching the second time I get the usual output and then, after 1 second:

```
TypeError: Cannot read property 'pop' of undefined
    at CheckpointTrie.Trie._updateNode (/Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:360:24)
    at /Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:107:16
    at /Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:461:14
    at processNode (/Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:471:23)
    at /Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:457:5
    at /Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:180:7
    at /Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:75:7
    at /Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
    at /Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:269:32
    at /Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
    at /Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:71:7
    at /Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:157:9
    at /Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/lib/database/levelupobjectadapter.js:41:16
    at /Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/level-sublevel/shell.js:101:15
    at /Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/level-sublevel/nut.js:121:19
    at /Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/encoding-down/index.js:51:21
    at /Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/node_modules/cachedown/index.js:58:21
    at ReadFileContext.callback (/Users/koirikivi/.nvm/versions/node/v8.11.2/lib/node_modules/ganache-cli/node_modules/ganache-core/lib/database/filedown.js:26:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

This happens with at least the following ganache versions:
- Ganache CLI v6.2.3 (ganache-core: 2.3.1).
- Ganache CLI v6.2.0 (ganache-core: 2.3.0)

Doesn't happen with 6.1.8. 

My OS is `macOS High Sierra 10.13.5 (17F77)` and nodejs `v8.11.2` if that matters. Installing ganache with `npm install -g ganache-cli@<insert version>`.

**Comment by davidmurdoch** [comment] 2018-11-27 14:57
@tsuberim, @koirikivi. Thanks for the info! I'll try to track this issue down today.

**Comment by ccowell** [comment] 2018-11-28 02:52
@tsuberim and @koirikivi Thanks for reporting this issue. I was able to confirm the crashes and will look into a fix soon.

**Comment by benjamincburns** [comment] 2018-11-29 01:18
This seems to be a duplicate of #407 - let's track this fix over there.

**Comment by benjamincburns** [comment] 2018-11-29 01:34
Apologies, I spoke too soon on this issue, it's not a dupe of #407.

**Comment by benjamincburns** [comment] 2018-12-06 00:57
Leaving this issue open until we have a fix, but we've reverted the change which causes this problem.

**Comment by benjamincburns** [comment] 2018-12-07 00:14
Fix for this inbound. Was a silly mistake that resulted in a rather hard to diagnose error.

**Closed as completed** 2018-12-07 23:25 UTC
Labels: bug, priority-high

**Comment by InoMurko** [comment] 2019-11-27 12:49
Hi, I think there was a regression on this particular issue. I'm getting similar error:
```
geth_1              | Listening on 0.0.0.0:8545
geth_1              | TypeError: Cannot read property 'pop' of undefined
geth_1              |     at c.g._updateNode (/app/ganache-core.docker.cli.js:25:199572)
geth_1              |     at /app/ganache-core.docker.cli.js:25:197581
geth_1              |     at /app/ganache-core.docker.cli.js:25:201092
geth_1              |     at e (/app/ganache-core.docker.cli.js:25:200564)
geth_1              |     at /app/ganache-core.docker.cli.js:25:201023
geth_1              |     at /app/ganache-core.docker.cli.js:25:198133
geth_1              |     at /app/ganache-core.docker.cli.js:2:194795
geth_1              |     at /app/ganache-core.docker.cli.js:25:392
geth_1              |     at /app/ganache-core.docker.cli.js:25:5735
geth_1              |     at /app/ganache-core.docker.cli.js:25:317
geth_1              |     at /app/ganache-core.docker.cli.js:2:194773
geth_1              |     at /app/ganache-core.docker.cli.js:25:197973
geth_1              |     at /app/ganache-core.docker.cli.js:61:1412187
geth_1              |     at /app/ganache-core.docker.cli.js:61:1407013
geth_1              |     at /app/ganache-core.docker.cli.js:61:1404376
geth_1              |     at /app/ganache-core.docker.cli.js:32:80653
```

I tried this with 
```
Status: Downloaded newer image for trufflesuite/ganache-cli:next
Creating elixir-omg_geth_1 ... done
Attaching to elixir-omg_geth_1
geth_1              | Ganache CLI v6.8.1-beta.0 (ganache-core: 2.9.1-beta.0)
geth_1              | (node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
and
```
Status: Downloaded newer image for trufflesuite/ganache-cli:latest
Creating elixir-omg_geth_1 ... done
Attaching to elixir-omg_geth_1
geth_1              | Ganache CLI v6.7.0 (ganache-core: 2.8.0)
geth_1              | (node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

My flags are:
```
ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - "8546"
      - "8545"
    volumes:
      - ./data/ganache/data:/data
    healthcheck:
      test: ping geth:8545 -c 1
      interval: 10s
      timeout: 5s
      retries: 10
    hostname: geth
    entrypoint: 
      - node
      - /app/ganache-core.docker.cli.js
      - --blockTime 
      - '0.5'
      - --deterministic 
      - --db
      - /data/
      - --account_keys_path 
      - /data/account_keys.txt
      - --defaultBalanceEther 
      - '100000'
      - --unlock 
      - "0"
      - --unlock 
      - "1"
      - --mnemonic 
      - 'myth like bonus scare over problem client lizard pioneer submit female collect'
     - --account
      - "0xd885a307e35738f773d8c9c63c7a3f3977819274638d04aaf934a1e1158513ce,100000000000000000000000"
      - --account
      - "0xd885a307e35738f773d8c9c63c7a3f3977819274638d04aaf934a1e1158513ce,100000000000000000000000"
      - --account
      - "0x6f30f140fd4724519e5017c0895f158d68bbbe4a81c0c10dbb25a0006e348807,100000000000000000000000"
```

What I was trying to do is create a database snapshot by starting ganache and deploying plasma contracts later. Once the deployment finished, I `docker stop <ganache node id>`. And saved the data directory. A restart of ganache from that same directory would produce an error.

**Comment by mahmoudafer** [comment] 2020-12-20 17:17
I'm getting this error on ganache-cli v6.12.1 on Node v15.4.0
the command I'm using is: 

`ganache-cli -d --db ./blockchain/db -i 1 --accounts 700 --deterministic -l 1000000000000000 -e 10000000 -g 1500000 -q --mnemonic="MY MNEMONIC"`

the error:

`TypeError: cannot read property 'pop' of undefined at e.value (/FULL/PATH/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:219266)`
